---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.yum:
      update_cache: yes

  - name: install_apache and php package
    ansible.builtin.yum:
      name: 
      - httpd
      - php
      state: present
    when: ansible_distribution == "CentOS"
