---
- hosts: all
  tags: always
  become: true
  tasks:



  - name: install updates
    tags: always
    dnf:
     update_only: yes
     update_cache: yes
    when: ansible_distribution == "CentOS"


- hosts: web_servers
  become: true
  tasks:

  - name: install_apache and php package
    tags: apache,centos,httpd
    dnf:
      name: 
      - httpd
      - php
      state: present
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,httpd
    copy:
      src: default.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
      





- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    ansible.builtin.yum:
      name: 
       - mariadb
      state: present
    when: ansible_distribution == "CentOS"
      

