---
- hosts: all
  tags: always
  become: true
  tasks:



  - name: update repo updates
    tags: always
    dnf:
     update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"


- hosts: web_servers
  become: true
  tasks:

  - name: install_apache and php package
    tags: apache,centos,httpd
    dnf:
      name: 
      - httpd
      - php
      state: present
    when: ansible_distribution == "CentOS"

  - name: start httpd centos
    tags: apache,centos,httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"  
    

  - name: add ssh key for simone
    tags: always
    ansible.builtin.cs_role:
      ssh_roles
    ansible.builtin.authorized_key:
      user: simone
      key: "{{ keys }}"
  

  - name: copy default html file for site
    tags: apache,httpd
    copy:
      src: default.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstations
  become: true
  tasks:
  - name: install unzip
    ansible.builtin.package:
      name: unzip







- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    ansible.builtin.yum:
      name: 
       - mariadb
      state: present
    when: ansible_distribution == "CentOS"
      

